# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('start_date', models.DateField(max_length=30)),
                ('start_time', models.TimeField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainer_exp', models.CharField(max_length=30)),
                ('mode_of_training', models.CharField(max_length=30)),
            ],
        ),
    ]
