# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_auto_20210706_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=100),
        ),
    ]
