# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0005_auto_20210706_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('company', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
