# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-06 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0006_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='datetime',
        ),
    ]
