# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-06 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0007_remove_feedback_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
